[project]
name = "mongo-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.0",
    "openfoodfacts>=3.3.0",
    "pandas>=2.3.3",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.1",
]
